### ISSUE TITLE
Example 8 does not print correct stats

### ISSUE THREAD

**Issue by clundst** [mat-adamec/PyHEP2020-Coffea-Analysis#14]
In example 8:

for key, value in output['cutflow'].items():
    print(key, value)

does not give the stats (as it does in, say, example 3).

**Comment by mat-adamec** [comment]
This is because nothing actually gets added to cutflow throughout the analysis. It's not a problem with the dictionary, but a problem with me not putting anything into the dictionary!

I'll go back through and save some info. I think it got removed when I was updating to coffea 0.7, because example 8 had to be redone completely.

**Comment by mat-adamec** [comment]
Fixed in 05c409b664b105a4a7e2cb295235f0c03245f970.
