### ISSUE TITLE
Example 8 fails with awkward 1.7.0

### ISSUE THREAD

**Issue by holzman** [mat-adamec/PyHEP2020-Coffea-Analysis#22]
Saw this while trying to run through examples on the EAF.

You can reproduce this by doing a `pip install awkward==1.7.0` on both the scheduler and workers, in which case:

```/tmp/ipykernel_498/64077513.py in process()
     60 
     61         # Remove elements of the closest pairs from leptons, because we want the pt of the third lepton.
---> 62         trileptons_no_pair = trileptons[(ak.local_index(trileptons) != ak.flatten(closest_pairs.i0)) & (ak.local_index(trileptons) != ak.flatten(closest_pairs.i1))]
     63 
     64         # Find the highest-pt lepton out of the ones that remain.
[ ... ]
ValueError: cannot broadcast RegularArray of size 1751 with RegularArray of size 2929

**Comment by oshadura** [comment]
@mat-adamec could you please take a look? Thanks!

**Comment by mat-adamec** [comment]
This should be fixed now with https://github.com/CoffeaTeam/coffea-casa-tutorials/commit/7e5c72ab003cb12e4d7a455e32bf6197675eba30. Turns out the default behavior of ak.fill_none() changed between these versions from axis=0 (the least-deep axis) to axis=-1 (the most-deep axis), so that broke things.

I've also reran the other examples to ensure they work with awkward 1.7.0, and they all seem to be good!
